apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "helmut.weeger@telekom.de"
namespace: instavote

